"Generated by paket2bazel"

load("@rules_dotnet//dotnet:defs.bzl", "nuget_repo")

def Main():
    "Main"
    nuget_repo(
        name = "main",
        packages = [
            ("Google.Protobuf", "3.24.1", "sha512-5uHrs7GlEkwtB6PQRWb2WmwQRAE0Gh/oG/uCfPl++T+BhHSmcr1ztbGE/BugHBqnjfdQfiEkibDfagKavoRmog==", ["https://api.nuget.org/v3/index.json"], None, ["System.Memory", "System.Runtime.CompilerServices.Unsafe"], []),
            ("Microsoft.NETCore.Platforms", "7.0.4", "sha512-mcQWjuDBh4WHGG4WcBI0k025WAdA2afMm6fs42sm1f+3gRyNQUiuMVT5gAWNUGSHmlu6qn/TCnAQpfl4Gm6cBw==", ["https://api.nuget.org/v3/index.json"], None, [], []),
            ("NETStandard.Library", "2.0.3", "sha512-548M6mnBSJWxsIlkQHfbzoYxpiYFXZZSL00p4GHYv8PkiqFBnnT68mW5mGEsA/ch9fDO9GkPgkFQpWiXZN7mAQ==", ["https://api.nuget.org/v3/index.json"], None, ["Microsoft.NETCore.Platforms"], []),
            ("System.Buffers", "4.5.1", "sha512-gNphWOVbm89+C15jebnPRaYykU8De1PFv1YJV24814IfeGGVa3PXRHDS0MLlbdI1pe9Mpv/n4ZK4INwtAjqv8g==", ["https://api.nuget.org/v3/index.json"], None, [], []),
            ("System.Memory", "4.5.5", "sha512-6MjlNsl7lKw0Q8lAsw2tQ89ul9x6jD2Yk3EEj+dOFoYGOE9eAUO9wNhvd4O/n97oQXlkyzqKXXUnE+kLElFy3A==", ["https://api.nuget.org/v3/index.json"], None, ["System.Buffers", "System.Numerics.Vectors", "System.Runtime.CompilerServices.Unsafe"], []),
            ("System.Numerics.Vectors", "4.5.0", "sha512-nATsBTD2CKr4AYN6eRszhX4sptImWmBJwB/U6XKCWWfnCcrTBw8XSCm3QA9gjppkHTr8OkXUY21MR91D3QZXsw==", ["https://api.nuget.org/v3/index.json"], None, [], []),
            ("System.Runtime.CompilerServices.Unsafe", "6.0.0", "sha512-1AVzAb5OxJNvJLnOADtexNmWgattm2XVOT3TjQTN7Dd4SqoSwai1CsN2fth42uQldJSQdz/sAec0+TzxBFgisw==", ["https://api.nuget.org/v3/index.json"], None, [], []),
        ],
    )
